# Generated by Django 3.2.6 on 2021-08-04 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiTable',
            fields=[
                ('studentdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inheritance.studentdetail')),
                ('st_class', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=3)),
                ('head_teacher', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('inheritance.studentdetail',),
        ),
        migrations.RenameModel(
            old_name='StudentDetails',
            new_name='StudentDetail',
        ),
    ]
