# Generated by Django 3.2.6 on 2021-08-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0002_auto_20210804_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiTable',
            new_name='MultiTableModel',
        ),
    ]
