# Generated by Django 3.2.6 on 2021-08-04 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0003_rename_multitable_multitablemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='multitablemodel',
            name='studentdetail_ptr',
        ),
        migrations.AddField(
            model_name='multitablemodel',
            name='dept_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inheritance.dept'),
            preserve_default=False,
        ),
    ]
